version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache-stretch-node-browsers
        ports: 80:80
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_DATABASE: log_smart_test
          MYSQL_USER: log_smart_test
          MYSQL_PASSWORD: log_smart_test
          MYSQL_ROOT_PASSWORD: log_smart_test
      - image: mongo:3.6
    working_directory: ~/log-smart-choice
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libicu-dev g++ mysql-client
          sudo pecl install mongodb
          echo "extension=mongodb.so" | sudo tee /usr/local/etc/php/conf.d/mongodb.ini
          sudo docker-php-ext-install pdo
          sudo docker-php-ext-install pdo_mysql
          sudo apt-get install mysql-client
          mysql -h 127.0.0.1 -u root --password="log_smart_test" -e "GRANT ALL PRIVILEGES ON log_smart_test.* TO 'log_smart_test'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
      - run: |
          sudo rm -rf /var/www/html
          sudo ln -s ~/log-smart-choice/public /var/www/html
          cd ~/log-smart-choice
          cp .env.testing .env
          composer update
          composer install --ignore-platform-reqs
          npm install
          sudo a2enmod rewrite && sudo service apache2 start
      - run: |
          php artisan migrate
          php artisan key:generate
          php artisan voyager:install
          php artisan passport:install
          npm run dev
      - run: ./vendor/phpcheckstyle/phpcheckstyle/phpcheckstyle --src . --exclude ./vendor --exclude ./database/migrations --exclude ./storage --exclude ./resources/views --outdir report --config ./check_php.xml
      - run: ./vendor/bin/phpunit