FROM php:7.3-apache

RUN apt-get update && apt-get install -y \
		git \
		unzip \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libmcrypt-dev \
        default-mysql-client \
        npm \
        vim \
    && pecl install mongodb \
    && docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- \
--install-dir=/usr/bin --filename=composer && chmod +x /usr/bin/composer

RUN echo "extension=mongodb.so" | tee /usr/local/etc/php/conf.d/mongodb.ini

COPY ./docker-config/000-default.conf /etc/apache2/sites-enabled/000-default.conf

COPY ./docker-config/ports.conf /etc/apache2/ports.conf
