<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class CityController extends VoyagerBaseController
{

    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}