<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\District;
use App\Models\Station;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

use function PHPSTORM_META\map;

/**
 * Class ImportManagementSystemController
 * @package App\Http\Controllers
 */
class ImportManagementSystemController extends VoyagerBaseController
{
    /**
     * @param Request $request
     * @return mixed
     */

    const LIMIT_COL_IMPORT = 5000;
    const LIMIT_COL_IMPORT_CUSTOMER = 1000;

    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function importStation(Request $request)
    {
        
        $colRegionCode = 0;
        $colTranCompanyCode = 1;
        $colStationCode = 2;
        $colTranCompanyFullName = 3;
        $colTranCompanyShortName = 4;
        $colStationOldName = 5;
        $colStationName = 6;
        $colNumberChange = 7;
        $colValueChange = 8;

        $validateGroup = array(
            $colTranCompanyFullName = 3,
            $colTranCompanyShortName = 4,
            // $colStationOldName = 5,
            $colStationName = 6,
        );

        DB::beginTransaction();
        try {
            $fileExt = $request->file('import_file')->getClientOriginalExtension();
            if ($fileExt != 'csv') {
                return redirect()->back()->with([
                    'message'    => 'Wrong format',
                    'alert-type' => 'error',
                ]);
            }
            $fileNameToStore = 'importStation' . '-' . date('Y-m-d') . '.' . $fileExt;
            $request->file('import_file')->storeAs('public/station/', $fileNameToStore);
            $row = 1;
            $errors = [];

            // read file
            if (($handle = fopen(storage_path('app/public/station/' . $fileNameToStore), "r")) !== FALSE) {
                $dataImport = array();
                while (($data = fgetcsv($handle, self::LIMIT_COL_IMPORT, ",")) !== FALSE) {
                    $isRowError = false;
                    foreach($validateGroup as $validateItem) {
                        if (empty($data[$validateItem])) {
                            $errors[][$validateItem] = 'Row:' . $row . ', data: ' . $data[$validateItem] . ' is not empty ';
                            $isRowError = 'Row:' . $row . ', data: ' . $data[$validateItem] . ' is not empty ';
                            break;
                        }

                        // validate japanese
                        if (!preg_match('/[\x{4E00}-\x{9FBF}\x{3040}-\x{309F}\x{30A0}-\x{30FF}]/u', $data[$validateItem])) {
                            $errors[][$validateItem] = 'Row: ' . $row . ', data: ' . $data[$validateItem] . ' is not japanese ';
                            $isRowError = 'Row: ' . $row . ', data: ' . $data[$validateItem] . ' is not japanese ';
                            break;
                        }

                        // special character
                        if (preg_match("/[!@#$%^&*(),.?\":{}|<>]/i", $data[$validateItem])) {
                            $errors[][$validateItem] = 'Row: ' . $row . ', data: ' . $data[$validateItem] . 'in not special character ';
                            $isRowError = 'Row: ' . $row . ', data: ' . $data[$validateItem] . 'in not special character ';
                            break;
                        }
                    }
                    if (!$isRowError) {
                        $dataImport = array(
                            'region_code' => intval($data[$colRegionCode]),
                            'tran_company_code' => intval($data[$colTranCompanyCode]),
                            'station_code' => intval($data[$colStationCode]),
                            'tran_company_full_name' => trim($data[$colTranCompanyFullName]),
                            'tran_company_short_name' => trim($data[$colTranCompanyShortName]),
                            'old_name' => trim($data[$colStationOldName]),
                            'name' => trim($data[$colStationName]),
                            'number_change' => intval($data[$colNumberChange]),
                            'value_change' => intval($data[$colValueChange])
                        );
                    }
                    
                    $this->_importStationData($dataImport);
                    $row++;
                }
                fclose($handle);
            }

            if (!empty($errors)) {
                DB::rollBack();
                return redirect()->back()->with([
                    'message'    => 'Import fail',
                    'alert-type' => 'error',
                ])->withErrors($errors);
            }

            DB::commit();

            return redirect()->back()->with([
                'message'    => 'Import success',
                'alert-type' => 'success',
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error($e->getMessage());
            return redirect()->back()->with([
                'message'    => 'Import fail',
                'alert-type' => 'error',
            ]);
        }
    }


    public function ImportCustomer(Request $request)
    {
        $colEmail = 1;
        $colPassword = 2;
        $colName = 4;
        $colLastName = 5;
        $colLandLine = 6;
        $colDistrict = 7;
        $colPriceMin = 8;
        $colPriceMax = 9;
        $colSquareMin = 10;
        $colSquareMax = 11;
        $validateGroup = array(
            $colEmail = 1,
            $colPassword= 2,
            $colName = 4,
            $colDistrict = 7,
            $colPriceMin = 8,
            $colPriceMax = 9,
            $colSquareMin = 10,
            $colSquareMax = 11,
        );
        DB::beginTransaction();
        try {
            $fileExt = $request->file('import_file')->getClientOriginalExtension();
            if ($fileExt != 'csv') {
                return redirect()->back()->with([
                    'message'    => 'Wrong format',
                    'alert-type' => 'error',
                ]);
            }
            $fileNameToStore = 'importCustomers' . '-' . date('Y-m-d') . '.' . $fileExt;
            $request->file('import_file')->storeAs('public/customer/', $fileNameToStore);
            $row = 1;
            $errors = [];

            // read file
            if (($handle = fopen(storage_path('app/public/customer/' . $fileNameToStore), "r")) !== FALSE) {
                $dataImport = [];
                $header = [];
                while (($data = fgetcsv($handle, self::LIMIT_COL_IMPORT_CUSTOMER, ",")) !== FALSE) {
                    if($row == 1) {
                        $header = $data;
                        $row++;
                        continue; 
                    }
                    foreach($validateGroup as $validateItem) {
                        // empty col
                        if ($data[$validateItem] == '') {
                            $errors[][$validateItem] = 'Row:' . $row . ', data: '. $data[$validateItem]. ' in ' . $header[$validateItem] . ' is not empty ';
                            break;
                        }

                        // check value number
                        if ($validateItem == 8 || $validateItem == 9 || $validateItem == 10 || $validateItem == 11) {
                            if (!preg_match('/\d/', $data[$validateItem])) {
                                $errors[][$validateItem] = 'Row:' . $row . ', data: '. $data[$validateItem]. ' in ' . $header[$validateItem] . ' is not number ';
                                break;
                            }
                        }

                        // validate email
                        if ($validateItem == 1) {
                            if (!filter_var($data[$validateItem], FILTER_VALIDATE_EMAIL)) {
                                $errors[][$validateItem] = 'Row: ' . $row . ', data: ' . $data[$validateItem]. ' in ' . $header[$validateItem] . ' is wrong format email ';
                                break;
                            }

                            if ($this->_checkEmailExisted($data[$validateItem])) {
                                $errors[][$validateItem] = 'Row: ' . $row . ', data: ' . $data[$validateItem]. ' in ' . $header[$validateItem] . ' is existed ';
                                break;
                            }
                        }

                        // validate district
                        if ($validateItem == 7) {
                            if (!$this->_checkDistrictExisted($data[$validateItem])) {
                                $errors[][$validateItem] = 'Row: ' . $row . ', data: ' . $data[$validateItem]. ' in ' . $header[$validateItem] . ' is not existed ';
                                break;
                            }
                        }

                        if (empty($errors)) {
                            $districtNew = explode(',', $data[$colDistrict]);
                            $price = [
                                'min' => intval($data[$colPriceMin]),
                                'max' => intval($data[$colPriceMax]),
                            ];
                            $square = [
                                'min' => intval($data[$colSquareMin]),
                                'max' => intval($data[$colSquareMax])
                            ];
                            $announcementCondition = [
                                'city' => $districtNew,
                                'price' => $price,
                                'square' => $square,
                            ];

                            $dataImport[$row] = [
                                'email' => $data[$colEmail],
                                'name' => $data[$colName],
                                'last_name' => $data[$colLastName],
                                'password' => Hash::make($data[$colPassword]),
                                'announcement_condition' => json_encode($announcementCondition),
                                'send_announcement' => Customer::SEND_ANNOUNCEMENT,
                                'status' => Customer::ACTIVE,
                                'land_line' => $data[$colLandLine],
                                'created_at' => date('Y-m-d H:i:s'),
                                'updated_at' => date('Y-m-d H:i:s'),
                            ];
                        }
                    }
                    $row++;
                }
                fclose($handle);
            }

            if (!empty($errors)) {
                DB::rollBack();
                return redirect()->back()->with([
                    'message'    => 'Import fail',
                    'alert-type' => 'error',
                ])->withErrors($errors);
            }

            $this->_importCustomerData($dataImport);
            DB::commit();

            return redirect()->back()->with([
                'message'    => 'Import success',
                'alert-type' => 'success',
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error($e->getMessage());
            return redirect()->back()->with([
                'message'    => 'Import fail',
                'alert-type' => 'error',
            ]);
        }
    }

    /**
     * @param $data
     */
    private function _importStationData($data)
    {
        $colUpdate = array(
            'region_code',
            'tran_company_code',
            'station_code',
            'tran_company_full_name',
            'tran_company_short_name',
            'old_name',
            'number_change',
            'value_change'
        );
        Station::upsert([$data], ['name'], $colUpdate);
    }

    private function _checkEmailExisted($email) {
        $customer = Customer::where('email', $email)->first();
        if ($customer) {
            return true;
        }
        return false;
    }

    private function _checkDistrictExisted($districts) {
        $districts = District::whereIn('name', explode(',', $districts))->get();
        if ($districts) {
            return true;
        }
        return false;
    }

    private function _importCustomerData($data)
    {
        return Customer::insert($data);
    }
}
