<?php

namespace App\Http\Controllers;


use App\Http\Traits\CustomAdminVoyager;
use Illuminate\Http\Request;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class TagPostController extends VoyagerBaseController
{

    use CustomAdminVoyager;

    /**
     * @param Request $request
     * @return mixed
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
