<?php


namespace App\Http\Controllers;


use App\Http\Requests\StoreUserRequest;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class UserControllers extends VoyagerBaseController
{

    public function index(StoreUserRequest $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}